### ISSUE TITLE
Simple Object Files

### ISSUE THREAD

**Issue by oakmac** [oakmac/open-ideas#2]
There is not a good file format for structured data when you want to store raw text. JSON requires you to escape strings, and YAML has many special character sequences.

You could use Markdown for this - like @shaunlebron does for [Parinfer examples](https://github.com/shaunlebron/parinfer/tree/master/lib/test/cases) - by being disciplined about what you put in the file, but you would still have to follow Markdown's syntax rules and write a custom parser for every different format.

There should be a small library for storing raw text as an object / hash-map. You could just pick one delimiter and make it configurable depending on what is being stored in the text.

This idea is inspired from how examples are stored in [autocomplete.js](https://github.com/oakmac/autocompletejs/tree/master/examples) and [chessboard.js](https://github.com/oakmac/chessboardjs/tree/master/examples).

**Comment by shaunlebron** [comment]
:+1:

**Comment by oakmac** [comment]
https://github.com/oakmac/kidif.js
